# Generated by Django 5.2.3 on 2025-06-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_metodopago_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Método principal'),
        ),
    ]
